nitf:
  <entity>: articles
  <primary_key>: /nitf/head/docdata/doc-id/@id-string
  <fields>:
    /nitf/head/title: title
    /nitf/head/pubdata/@date.publication: date
    /nitf/head/pubdata/@ex-ref: url
    /nitf/head/meta[14]/@content: print_headline
    /nitf/head/meta[4]/@content: credit
    /nitf/head/meta[5]/@content: edition
    /nitf/head/meta[16]/@content: section
    /nitf/head/meta[17]/@content: subsection
    /nitf/head/meta[12]/@content: print_page_number
    /nitf/head/meta[13]/@content: print_section
    /nitf/body/body.head/byline: author
    /nitf/body/body.head/abstract: abstract
    /nitf/body/body.content: paragraphs

head/docdata/key-list:
  <entity>: keywords
  <primary_key>: /nitf/head/docdata/doc-id/@id-string
  <fields>:
      "keyword/@key":
        <fieldname>: keywords
        <joiner>: " || "

head/docdata/identified-content:
  <entity>: locations
  <primary_key>: /nitf/head/docdata/doc-id/@id-string
  <fields>:
      "/nitf/head/docdata/identified-content/location":
        <fieldname>: locations
        <joiner>: " || "
    
head/docdata/identified-content:
  <entity>: people
  <primary_key>: /nitf/head/docdata/doc-id/@id-string
  <fields>:
      "person":
        <fieldname>: people
        <joiner>: " || "
